jwt:
  secret: '@!#$%j3vonn3L@!ng@!#$%j3vonn3L@!ng@!#$%j3vonn3L@!ng@!#$%j3vonn3L@!ng@!#$%j3vonn3L@!ng@!#$%j3vonn3L@!ng@!#$%j3vonn3L@!ng'

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/supportportal
    password:
    username:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
      add-mappings: false

